name: "Dependabot Automerge - Action"
on:
  pull_request_target:
    branches:
      - main
jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: ${{ secrets.MYTOKEN }}
          command: "merge rebase"
          target: minor
